### ISSUE TITLE
date on top of the article

### ISSUE THREAD

**Issue by phanirithvij** [evanfields/evanfields.github.io#1]
I visited https://evanfields.github.io/No-Perfect-Geo-Grid/ but could not determine the date (until scrolling to the very end), which I think will force the reader to reconsider reading an article. I think date on top, below the title is preferred.

**Comment by evanfields** [comment]
Thanks for the suggestion - and for reading! I think you're right. I'm extremely not good at web programming but will take a look and see if the style is easy to change.

**Comment by evanfields** [comment]
It was easy to move the date to the top within the post, but it'd be good to also do it in the blog view...

**Comment by phanirithvij** [comment]
I don't know jekyll either (used hugo before) but maybe this #2 will work?

**Comment by evanfields** [comment]
Looks great, thanks!
